version: 2

updates:
  - package-ecosystem: bun
    directories:
      - /
      - /playground
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(dependencies)"
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(dependencies)"
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development

